- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/deployment.yaml
- Charts/qtest-insights/values.yaml
Integrating subpath for volumeMounts.
> Insights - Update helm chart

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights-etl/templates/deployment.yaml
- Charts/qtest-insights-etl/values.yaml
Integrating subpath for volumeMounts.
> InsightsEtl - update helm chart

- .github/CODEOWNERS
https://jira.tricentis.com/browse/CLDOPS-2904
Adding codowners approval for qtest helm chart
> CLDOPS-2904: adding codowners

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/deployment.yaml
- Charts/qtest-insights/values.yaml
Raise Insights version and change 3 paths to ephemeral storage
> Update from Tricentis-qTest/qtest-chart

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/deployment.yaml
- Charts/qtest-mgr/values.yaml
* Update Manager version from 2023.5.7 to 2024.1
* Manager chart now supports option for defining Resources per deployment (ui, api, poller, notifcation) instead of using shared definition
> Update Manager version from 2023.5.7 to 2024.1

- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/templates/hpa.yaml
- Charts/qtest-scenario/values.yaml
Update Scenario version from 2023.5.7 to 2024.1
> Update Scenario version from 2023.5.7 to 2024.1

- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/hpa.yaml
- Charts/qtest-launch/values.yaml
Update Launch version from 2023.5.7 to 2024.1
> Update Launch version from 2023.5.7 to 2024.1

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/configmap.yaml
- Charts/qtest-parameters/templates/deployment.yaml
- Charts/qtest-parameters/templates/hpa.yaml
- Charts/qtest-parameters/values.yaml
Update Parameter version from 2023.5 to 2024.1
> Update Parameter version from 2023.5 to 2024.1

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/hpa.yaml
- Charts/qtest-session/values.yaml
Update Session version from 2023.5.5 to 2024.1
> Update Session version from 2023.5.5 to 2024.1

- .github/workflows/ci.yaml
Adjust CI check in order to download dependencies during check rather than keeping them in VCS
> Adjust CI check

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/values.yaml
Release manager version "2024.2.1.1.op"
> Manager 2024.2 release

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/values.yaml
Release Parameters version "2024.2"
> Release Parameters version "2024.2"

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights-etl/templates/deployment.yaml
- Charts/qtest-insights-etl/values.yaml
Release InsightsETL version "v2024.2.op"
> Release Insights version "v2024.2.op"

- Charts/qtest-launch/values.yaml
- Charts/qtest-mgr/values.yaml
- Charts/qtest-parameters/values.yaml
- Charts/qtest-scenario/values.yaml
- Charts/qtest-session/values.yaml
> Fix formating

- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/values.yaml
> Release Scenario 2024.2

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/deployment.yaml
- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/deployment.yaml
- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/deployment.yaml
- Charts/qtest-pulse/Chart.yaml
- Charts/qtest-pulse/templates/deployment.yaml
- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/templates/deployment.yaml
- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/deployment.yaml
Fix topologySpread indentation for satellite apps
> Fix topologySpread indentation

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/configmap.yaml
- Charts/qtest-mgr/templates/deployment.yaml
- Charts/qtest-mgr/values.yaml
Update qTest Manager version 2024.3
> SRE-0: Update qTest Manager chart

- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/deployment.yaml
- Charts/qtest-launch/values.yaml
> Update Launch chart version

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights-etl/templates/deployment.yaml
> Update Insight ETL helm chart 1.5.0

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/deployment.yaml
- Charts/qtest-parameters/values.yaml
Update Parameters helm chart. It is a part of release.
> Update Parameters helm chart

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/deployment.yaml
> session fix deployment

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/configmap.yaml
- Charts/qtest-mgr/templates/deployment.yaml
- Charts/qtest-mgr/values.yaml
Revert part of the Manager config for encryption
> Revert part of the Manager config for encryption

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights-etl/templates/configmap.yaml
- Charts/qtest-insights-etl/values.yaml
Included changes:
- add DEPLOYMENT_ENV property to insights-etl to enable swith logging from plain text to json
> Update helm chart for Insights ETL

- .github/ct.yaml
Skip maintainers check during lint check
> Skip maintainers check

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/configmap.yaml
- Charts/qtest-insights/values.yaml
- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/configmap.yaml
- Charts/qtest-launch/templates/deployment.yaml
- Charts/qtest-launch/values.yaml
- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/configmap.yaml
- Charts/qtest-mgr/templates/deployment.yaml
- Charts/qtest-mgr/templates/hpa.yaml
- Charts/qtest-mgr/values.yaml
- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/configmap.yaml
- Charts/qtest-parameters/templates/deployment.yaml
- Charts/qtest-parameters/values.yaml
- Charts/qtest-pulse/Chart.yaml
- Charts/qtest-pulse/templates/configmap.yaml
- Charts/qtest-pulse/templates/deployment.yaml
- Charts/qtest-pulse/values.yaml
- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/templates/configmap.yaml
- Charts/qtest-scenario/templates/deployment.yaml
- Charts/qtest-scenario/values.yaml
- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/configmap.yaml
- Charts/qtest-session/templates/deployment.yaml
- Charts/qtest-session/values.yaml
Notable changes:
- maintainers updated to be just a link to the support portal
- AES keys and passwords setting in manager
- SSL options in all deployments
- minor fixes and cleanup
> PCR-5150 Release new version of charts due to 2024.3 SaaS release

- Charts/qtest-insights-etl/Chart.yaml
Forgot to raise a version of `insights-etl` in #231 so doing it now...
> PCR-5150 Fix insights-etl version

- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/templates/pdb.yaml
- Charts/qtest-scenario/values.yaml
SRE-2364 PDB creation for Scenario, tested on staging
> SRE-2364 PDB creation for Scenario

- Charts/qtest-pulse/Chart.yaml
- Charts/qtest-pulse/templates/pdb.yaml
- Charts/qtest-pulse/values.yaml
SRE-2364 PDB Charts Prod creation for `pulse` and `pulse-executor`
tested on staging
> SRE-2364 PDB creation for Pulse

- Charts/qtest-scenario/Chart.yaml
SRE-2364 Scenario Chart - rerun as last action didnt create chart properly
> SRE-2364 Scenario Chart

- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/pdb.yaml
- Charts/qtest-launch/values.yaml
SRE-2364 Launch PDB Chart creation
> SRE-2364 Launch PDB creation

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/pdb.yaml
- Charts/qtest-parameters/values.yaml
SRE-2364 Parameters PDB creation
> SRE-2364 Parameters PDB creation

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/pdb.yaml
- Charts/qtest-session/values.yaml
SRE-2364 Session PDB Charts creation
> SRE-2364 Session PDB Chart

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/deployment.yaml
Remove unused Insights/Session ReadOnly references
> Insights cleanup

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/deployment.yaml
- Charts/qtest-session/values.yaml
Remove unused Insights/Session ReadOnly references
> Session cleanup

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/values.yaml
Raise Insights version to 2024.4
> Insights 2024.4

- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/values.yaml
Raise Launch version to 2024.4
> Raise Launch version to 2024.4

- Charts/qtest-scenario/Chart.yaml
- Charts/qtest-scenario/values.yaml
Raise Scenario version to 2024.4
> Raise Scenario version to 2024.4

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/values.yaml
Raise Session version to 2024.4
> Raise Session version to 2024.4

- Charts/qtest-pulse/Chart.yaml
- Charts/qtest-pulse/values.yaml
> Raise Pulse version to 2024.4

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/values.yaml
Raise Parameters version to 2024.4
> Raise Parameters version to 2024.4

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/configmap.yaml
- Charts/qtest-mgr/values.yaml
Raise Manager version to 2024.4 + drop functionality that was moved directly to the application
> Raise Manager version to 2024.4

- Charts/qtest-mgr/Chart.yaml
Fix tag of Manager to 2024.4.0.6.op
> Manager version fix

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/values.yaml
> Fix image tag for Manager

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/configmap.yaml
- Charts/qtest-mgr/values.yaml
Adding new env for Intercom in Manager
> PCR-5306: Mgr chart update

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/templates/deployment.yaml
- Charts/qtest-mgr/templates/logging-configmap.yaml
- Charts/qtest-mgr/values.yaml
- Ability to mount logback.xml
> Release new version of chart with Manager 2025.2 release

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/templates/deployment.yaml
- Charts/qtest-parameters/values.yaml
>  Release new version of chart with Parameters 2025.2 release

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/templates/deployment.yaml
- Charts/qtest-session/templates/service.yaml
- Charts/qtest-session/values.yaml
>  Release new version of chart with Session 2025.2 release

- Charts/qtest-pulse/Chart.yaml
- Charts/qtest-pulse/templates/configmap.yaml
- Charts/qtest-pulse/templates/deployment.yaml
- Charts/qtest-pulse/templates/service.yaml
- Charts/qtest-pulse/values.yaml
- Add LaunchDarkly key
- Add websocket supprot
>  Release new version of chart with Pulse 2025.2 release

- Charts/qtest-parameters/Chart.yaml
> Fix Chart Version

- Charts/qtest-i-etl/Chart.yaml
- Charts/qtest-i-etl/templates/configmap.yaml
- Charts/qtest-i-etl/templates/deployment.yaml
- Charts/qtest-i-etl/templates/job-liquibase.yaml
- Charts/qtest-i-etl/templates/secret.yaml
- Charts/qtest-i-etl/values.yaml
PCR-5377 IETL new Charts, preparation for production deployment
> PCR-5377 IETL new Charts

- Charts/qtest-i-etl/Chart.yaml
- Charts/qtest-i-etl/templates/hpa.yaml
> PCR-5377 i-etl chart

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/values.yaml
> Release new version of chart with Insights 2025.2.1

- Charts/qtest-insights-etl/Chart.yaml
- Charts/qtest-insights-etl/templates/configmap.yaml
- Charts/qtest-insights-etl/values.yaml
- Update Image tag
- Remove UPDATEDB
- Point writeSessionsDBName to `sessions`
> Release new version of chart with Insights ETL 2025.2.0op

- Charts/qtest-launch/Chart.yaml
- Charts/qtest-launch/templates/service.yaml
- Charts/qtest-launch/values.yaml
- Update image tag
- Add name label to service ports
> Release new version of chart with Launch 2025.2.0

- Charts/qtest-parameters/Chart.yaml
- Charts/qtest-parameters/values.yaml
> Release new version of chart with Parameters 2025.2.0

- Charts/qtest-session/Chart.yaml
- Charts/qtest-session/values.yaml
> Release new version of chart with Session 2025.2.0

- Charts/qtest-insights/Chart.yaml
- Charts/qtest-insights/templates/configmap.yaml
- Charts/qtest-insights/templates/deployment.yaml
- Charts/qtest-insights/values.yaml
Add POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER support for Insights
> Insights 2025.2.3

- .github/ct.yaml
> SRE-4220: Remove unused Bitnami refs

- Charts/qtest-mgr/Chart.yaml
- Charts/qtest-mgr/values.yaml
Increase Manager version to 2025.2.8
> Increase Manager version to 2025.2.8
